import Hatchback from "@/public/icons/Hatchback";
import Sedan from "@/public/icons/Sedan";
import Sport from "@/public/icons/Sport";
import Suv from "@/public/icons/Suv";
import Head from "next/head";
import Link from "next/link";
import styles from "./Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={`flex justify-center items-center gap-4 font-semibold ${styles.aTagsContainer}`}>
          <Link href="/">
            Sedan
            <Sedan />
          </Link>
          <Link href="/">
            SUV
            <Suv />
          </Link>
          <Link href="/">
            Hatchback
            <Hatchback />
          </Link>
          <Link href="/">
            Sport
            <Sport />
          </Link>
        </div>
      </main>
    </>
  );
}
