import Categories from "@/components/Catgories";
import Head from "next/head";
import data from "../data/carsData";
import CarCard from "@/components/CarCard";
import { Josefin_Sans } from "next/font/google";
import Link from "next/link";

const josefin = Josefin_Sans({
  weight: ["700"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Categories />
        <h2
          className={`flex justify-center items-center font-bold text-2xl ${josefin.className} p-4`}
        >
          All Cars
        </h2>
        <div className="grid md:grid-cols-3 md:w-[80%] mx-auto">
          {data.map((item) => (
            <Link href={`/cars/${item.id}`} key={item.id}>
              <CarCard car={item} className="cursor-pointer"/>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}
